### ISSUE TITLE
Please_Run_This_First_To_Fetch_Big_Files.py 下载失败 KeyError: 'uhmp-big-file-v3.10'

### ISSUE THREAD

**Issue by xzz666** [binary-husky/unreal-map#8]
(base) F:\RLUE4\unreal-map-master>python Please_Run_This_First_To_Fetch_Big_Files.py
Download uhmap file manifest | 下载manifest目录文件
100%|████████████████████████████████████████████████████████████████████████████| 4.07k/4.07k [00:00<00:00, 1.37MiB/s]
Traceback (most recent call last):
  File "F:\RLUE4\unreal-map-master\Please_Run_This_First_To_Fetch_Big_Files.py", line 37, in <module>
    success = download_from_shared_server(f'uhmp-big-file-v{version}')
  File "F:\RLUE4\unreal-map-master\Please_Run_This_First_To_Fetch_Big_Files.py", line 21, in download_from_shared_server
    uhmap_url = manifest[key]
KeyError: 'uhmp-big-file-v3.10'

![image](https://github.com/binary-husky/unreal-map/assets/37150922/c478a95f-9290-414d-8754-1942643ee382)

**Comment by binary-husky** [comment]
sorry，I'm uploading

**Comment by binary-husky** [comment]
I'm skipping 3.10 and direct to 3.11

**Comment by binary-husky** [comment]
https://ageasga-my.sharepoint.com/:u:/g/personal/fuqingxu_yiteam_tech/EVmCQMSUWV5MgREWaxiz_GoBalBRV3DWBU3ToSJ5OTQaLQ?e=I8yjl9

**Comment by binary-husky** [comment]
we are working on it
https://github.com/binary-husky/unreal-map/pull/12

**Comment by Ballade-F** [comment]
> https://ageasga-my.sharepoint.com/:u:/g/personal/fuqingxu_yiteam_tech/EVmCQMSUWV5MgREWaxiz_GoBalBRV3DWBU3ToSJ5OTQaLQ?e=I8yjl9

Video link has expired
404 FILE NOT FOUND
